<?php

namespace AppBundle\Repository;

/**
 * EventDrawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventDrawRepository extends \Doctrine\ORM\EntityRepository
{
}
